server:
  port: 8080
spring:
  application:
    name: le_takeaway
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/le_takeaway?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  #redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    #password: 123456
    time-to-live: 1800000  #ms单位 30min
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    # 比如数据库中的表名是address_info，实体类中的属性名是addressInfo
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

le_takeaway:
  path: /Users/chenxiaole/learnTrain/javaProjects/tmp/


